const warframes = [
const warframes=[
{name:"Excalibur Prime",image:"https://static.wikia.nocookie.net/warframe/images/8/80/ExcaliburNewLook.png",abilities:{1:{name:"Slash Dash",sound:"https://static.wikia.nocookie.net/warframe/images/7/7f/SlashDash.ogg"},2:{name:"Radial Blind",sound:"https://static.wikia.nocookie.net/warframe/images/4/4d/RadialBlind.ogg"},3:{name:"Radial Javelin",sound:"https://static.wikia.nocookie.net/warframe/images/4/4a/RadialJavelin.ogg"},4:{name:"Exalted Blade",sound:"https://static.wikia.nocookie.net/warframe/images/5/5a/ExaltedBlade.ogg"}},augments:[{name:"Purging Slash",description:"Slash Dash remove buffs dos inimigos atingidos.",ability:1},{name:"Radiant Finish",description:"Radial Blind aumenta dano de finishers.",ability:2},{name:"Furious Javelin",description:"Radial Javelin aumenta dano por inimigo atingido.",ability:3},{name:"Chromatic Blade",description:"Exalted Blade ganha dano elemental baseado na cor da energia.",ability:4}]},

{name:"Ash Prime",image:"https://static.wikia.nocookie.net/warframe/images/3/3f/AshPrime.png",abilities:{1:{name:"Shuriken",sound:"https://static.wikia.nocookie.net/warframe/images/0/0e/Shuriken.ogg"},2:{name:"Smoke Screen",sound:"https://static.wikia.nocookie.net/warframe/images/1/1e/SmokeScreen.ogg"},3:{name:"Teleport",sound:"https://static.wikia.nocookie.net/warframe/images/7/7a/Teleport.ogg"},4:{name:"Blade Storm",sound:"https://static.wikia.nocookie.net/warframe/images/8/8b/BladeStorm.ogg"}},augments:[{name:"Seeking Shuriken",description:"Shuriken remove armadura dos inimigos.",ability:1},{name:"Smoke Shadow",description:"Aliados próximos recebem invisibilidade.",ability:2},{name:"Fatal Teleport",description:"Teleport executa finisher automaticamente.",ability:3},{name:"Rising Storm",description:"Blade Storm aumenta combo melee.",ability:4}]},

{name:"Atlas Prime",image:"https://static.wikia.nocookie.net/warframe/images/2/2c/AtlasPrime.png",abilities:{1:{name:"Landslide",sound:"https://static.wikia.nocookie.net/warframe/images/4/4c/Landslide.ogg"},2:{name:"Tectonics",sound:"https://static.wikia.nocookie.net/warframe/images/3/3a/Tectonics.ogg"},3:{name:"Petrify",sound:"https://static.wikia.nocookie.net/warframe/images/8/8a/Petrify.ogg"},4:{name:"Rumblers",sound:"https://static.wikia.nocookie.net/warframe/images/0/0a/Rumblers.ogg"}},augments:[{name:"Path of Statues",description:"Landslide deixa rastro petrificante.",ability:1},{name:"Tectonic Fracture",description:"Tectonics cria múltiplas paredes.",ability:2},{name:"Ore Gaze",description:"Petrify aumenta chance de loot.",ability:3},{name:"Rumbled",description:"Rumblers transforma Atlas em golem.",ability:4}]},

{name:"Banshee Prime",image:"https://static.wikia.nocookie.net/warframe/images/4/4a/BansheePrime.png",abilities:{1:{name:"Sonic Boom",sound:"https://static.wikia.nocookie.net/warframe/images/7/7d/SonicBoom.ogg"},2:{name:"Sonar",sound:"https://static.wikia.nocookie.net/warframe/images/0/0a/Sonar.ogg"},3:{name:"Silence",sound:"https://static.wikia.nocookie.net/warframe/images/3/3c/Silence.ogg"},4:{name:"Sound Quake",sound:"https://static.wikia.nocookie.net/warframe/images/8/8e/SoundQuake.ogg"}},augments:[{name:"Sonic Fracture",description:"Sonic Boom remove armadura.",ability:1},{name:"Resonance",description:"Sonar se recast automaticamente ao atingir pontos fracos.",ability:2},{name:"Savage Silence",description:"Silence aumenta dano de finishers.",ability:3},{name:"Resonating Quake",description:"Sound Quake vira explosões móveis.",ability:4}]},

{name:"Baruuk Prime",image:"https://static.wikia.nocookie.net/warframe/images/0/0c/BaruukPrime.png",abilities:{1:{name:"Elude",sound:"https://static.wikia.nocookie.net/warframe/images/4/4c/Elude.ogg"},2:{name:"Lull",sound:"https://static.wikia.nocookie.net/warframe/images/1/1e/Lull.ogg"},3:{name:"Desolate Hands",sound:"https://static.wikia.nocookie.net/warframe/images/3/3f/DesolateHands.ogg"},4:{name:"Serene Storm",sound:"https://static.wikia.nocookie.net/warframe/images/7/7a/SereneStorm.ogg"}},augments:[{name:"Reactive Storm",description:"Serene Storm ganha dano elemental adaptativo.",ability:4}]},

{name:"Chroma Prime",image:"https://static.wikia.nocookie.net/warframe/images/8/8e/ChromaPrime.png",abilities:{1:{name:"Spectral Scream",sound:"https://static.wikia.nocookie.net/warframe/images/4/4a/SpectralScream.ogg"},2:{name:"Elemental Ward",sound:"https://static.wikia.nocookie.net/warframe/images/0/0d/ElementalWard.ogg"},3:{name:"Vex Armor",sound:"https://static.wikia.nocookie.net/warframe/images/3/3e/VexArmor.ogg"},4:{name:"Effigy",sound:"https://static.wikia.nocookie.net/warframe/images/9/9f/Effigy.ogg"}},augments:[{name:"Afterburn",description:"Spectral Scream dispara projéteis.",ability:1},{name:"Everlasting Ward",description:"Elemental Ward permanece nos aliados.",ability:2},{name:"Vexing Retaliation",description:"Vex Armor causa dano ao ser atingido.",ability:3},{name:"Guided Effigy",description:"Effigy pode se mover.",ability:4}]},

{name:"Ember Prime",image:"https://static.wikia.nocookie.net/warframe/images/4/4b/EmberPrime.png",abilities:{1:{name:"Fireball",sound:"https://static.wikia.nocookie.net/warframe/images/9/9b/Fireball.ogg"},2:{name:"Immolation",sound:"https://static.wikia.nocookie.net/warframe/images/3/3c/Immolation.ogg"},3:{name:"Fire Blast",sound:"https://static.wikia.nocookie.net/warframe/images/2/2e/FireBlast.ogg"},4:{name:"Inferno",sound:"https://static.wikia.nocookie.net/warframe/images/4/4e/Inferno.ogg"}},augments:[{name:"Fireball Frenzy",description:"Fireball concede bônus de dano de fogo a aliados.",ability:1},{name:"Immolated Radiance",description:"Immolation concede resistência a aliados.",ability:2},{name:"Healing Flame",description:"Fire Blast cura Ember por inimigo atingido.",ability:3},{name:"Exothermic",description:"Inferno faz inimigos derrubarem orbes de energia.",ability:4}]},

{name:"Equinox Prime",image:"https://static.wikia.nocookie.net/warframe/images/7/7a/EquinoxPrime.png",abilities:{1:{name:"Metamorphosis",sound:"https://static.wikia.nocookie.net/warframe/images/3/3e/Metamorphosis.ogg"},2:{name:"Rest & Rage",sound:"https://static.wikia.nocookie.net/warframe/images/4/4f/RestRage.ogg"},3:{name:"Pacify & Provoke",sound:"https://static.wikia.nocookie.net/warframe/images/5/5e/PacifyProvoke.ogg"},4:{name:"Mend & Maim",sound:"https://static.wikia.nocookie.net/warframe/images/9/9d/MendMaim.ogg"}},augments:[{name:"Calm & Frenzy",description:"Rest & Rage se espalha para inimigos próximos.",ability:2},{name:"Peaceful Provocation",description:"Pacify & Provoke ganha bônus baseado em dano recebido.",ability:3},{name:"Energy Transfer",description:"Mend & Maim mantém carga ao trocar de forma.",ability:4}]},

{name:"Frost Prime",image:"https://static.wikia.nocookie.net/warframe/images/9/9f/FrostPrime.png",abilities:{1:{name:"Freeze",sound:"https://static.wikia.nocookie.net/warframe/images/4/4a/Freeze.ogg"},2:{name:"Ice Wave",sound:"https://static.wikia.nocookie.net/warframe/images/6/6d/IceWave.ogg"},3:{name:"Snow Globe",sound:"https://static.wikia.nocookie.net/warframe/images/1/1f/SnowGlobe.ogg"},4:{name:"Avalanche",sound:"https://static.wikia.nocookie.net/warframe/images/7/7c/Avalanche.ogg"}},augments:[{name:"Freeze Force",description:"Freeze concede bônus de dano de gelo a aliados.",ability:1},{name:"Ice Wave Impedance",description:"Ice Wave deixa rastro que reduz velocidade.",ability:2},{name:"Chilling Globe",description:"Snow Globe congela inimigos que entram.",ability:3},{name:"Icy Avalanche",description:"Avalanche concede armadura de gelo a aliados.",ability:4}]},

{name:"Gara Prime",image:"https://static.wikia.nocookie.net/warframe/images/4/4a/GaraPrime.png",abilities:{1:{name:"Shattered Lash",sound:"https://static.wikia.nocookie.net/warframe/images/2/2a/ShatteredLash.ogg"},2:{name:"Splinter Storm",sound:"https://static.wikia.nocookie.net/warframe/images/3/3e/SplinterStorm.ogg"},3:{name:"Spectrorage",sound:"https://static.wikia.nocookie.net/warframe/images/9/9c/Spectrorage.ogg"},4:{name:"Mass Vitrify",sound:"https://static.wikia.nocookie.net/warframe/images/8/8d/MassVitrify.ogg"}},augments:[{name:"Shattered Storm",description:"Shattered Lash renova Splinter Storm.",ability:1},{name:"Mending Splinters",description:"Splinter Storm cura aliados.",ability:2},{name:"Spectrosiphon",description:"Spectrorage faz inimigos derrubarem orbes de energia.",ability:3}]},

{name:"Garuda Prime",image:"https://static.wikia.nocookie.net/warframe/images/0/0c/GarudaPrime.png",abilities:{1:{name:"Dread Mirror",sound:"https://static.wikia.nocookie.net/warframe/images/8/8f/DreadMirror.ogg"},2:{name:"Blood Altar",sound:"https://static.wikia.nocookie.net/warframe/images/4/4e/BloodAltar.ogg"},3:{name:"Bloodletting",sound:"https://static.wikia.nocookie.net/warframe/images/7/7b/Bloodletting.ogg"},4:{name:"Seeking Talons",sound:"https://static.wikia.nocookie.net/warframe/images/9/9d/SeekingTalons.ogg"}},augments:[{name:"Dread Ward",description:"Dread Mirror concede invulnerabilidade ao matar.",ability:1}]},

{name:"Gauss Prime",image:"https://static.wikia.nocookie.net/warframe/images/4/4d/GaussPrime.png",abilities:{1:{name:"Mach Rush",sound:"https://static.wikia.nocookie.net/warframe/images/5/5a/MachRush.ogg"},2:{name:"Kinetic Plating",sound:"https://static.wikia.nocookie.net/warframe/images/8/8e/KineticPlating.ogg"},3:{name:"Thermal Sunder",sound:"https://static.wikia.nocookie.net/warframe/images/1/1e/ThermalSunder.ogg"},4:{name:"Redline",sound:"https://static.wikia.nocookie.net/warframe/images/3/3d/Redline.ogg"}},augments:[{name:"Mach Crash",description:"Mach Rush derruba inimigos.",ability:1}]},

{name:"Grendel Prime",image:"https://static.wikia.nocookie.net/warframe/images/8/8a/GrendelPrime.png",abilities:{1:{name:"Feast",sound:"https://static.wikia.nocookie.net/warframe/images/4/4c/Feast.ogg"},2:{name:"Nourish",sound:"https://static.wikia.nocookie.net/warframe/images/7/7d/Nourish.ogg"},3:{name:"Regurgitate",sound:"https://static.wikia.nocookie.net/warframe/images/8/8f/Regurgitate.ogg"},4:{name:"Pulverize",sound:"https://static.wikia.nocookie.net/warframe/images/3/3e/Pulverize.ogg"}},augments:[{name:"Regenerative Molt",description:"Nourish cura Grendel.",ability:2}]},

{name:"Harrow Prime",image:"https://static.wikia.nocookie.net/warframe/images/3/3a/HarrowPrime.png",abilities:{1:{name:"Condemn",sound:"https://static.wikia.nocookie.net/warframe/images/2/2e/Condemn.ogg"},2:{name:"Penance",sound:"https://static.wikia.nocookie.net/warframe/images/4/4f/Penance.ogg"},3:{name:"Thurible",sound:"https://static.wikia.nocookie.net/warframe/images/8/8d/Thurible.ogg"},4:{name:"Covenant",sound:"https://static.wikia.nocookie.net/warframe/images/0/0e/Covenant.ogg"}},augments:[{name:"Lasting Covenant",description:"Covenant dura mais ao matar inimigos.",ability:4}]},

{name:"Hildryn Prime",image:"https://static.wikia.nocookie.net/warframe/images/4/4f/HildrynPrime.png",abilities:{1:{name:"Balefire",sound:"https://static.wikia.nocookie.net/warframe/images/3/3e/Balefire.ogg"},2:{name:"Pillage",sound:"https://static.wikia.nocookie.net/warframe/images/4/4f/Pillage.ogg"},3:{name:"Haven",sound:"https://static.wikia.nocookie.net/warframe/images/7/7d/Haven.ogg"},4:{name:"Aegis Storm",sound:"https://static.wikia.nocookie.net/warframe/images/9/9d/AegisStorm.ogg"}},augments:[{name:"Blazing Pillage",description:"Pillage causa dano de fogo em inimigos afetados por Haven.",ability:2}]},

{name:"Hydroid Prime",image:"https://static.wikia.nocookie.net/warframe/images/7/7f/HydroidPrime.png",abilities:{1:{name:"Tempest Barrage",sound:"https://static.wikia.nocookie.net/warframe/images/3/3e/TempestBarrage.ogg"},2:{name:"Tidal Surge",sound:"https://static.wikia.nocookie.net/warframe/images/4/4f/TidalSurge.ogg"},3:{name:"Undertow",sound:"https://static.wikia.nocookie.net/warframe/images/8/8d/Undertow.ogg"},4:{name:"Tentacle Swarm",sound:"https://static.wikia.nocookie.net/warframe/images/9/9f/TentacleSwarm.ogg"}},augments:[{name:"Corroding Barrage",description:"Tempest Barrage aplica corrosão.",ability:1},{name:"Tidal Impunity",description:"Tidal Surge concede imunidade temporária.",ability:2},{name:"Curative Undertow",description:"Undertow cura aliados.",ability:3}]},

{name:"Inaros Prime",image:"https://static.wikia.nocookie.net/warframe/images/4/4d/InarosPrime.png",abilities:{1:{name:"Desiccation",sound:"https://static.wikia.nocookie.net/warframe/images/7/7e/Desiccation.ogg"},2:{name:"Devour",sound:"https://static.wikia.nocookie.net/warframe/images/8/8a/Devour.ogg"},3:{name:"Sandstorm",sound:"https://static.wikia.nocookie.net/warframe/images/5/5e/Sandstorm.ogg"},4:{name:"Scarab Swarm",sound:"https://static.wikia.nocookie.net/warframe/images/6/6f/ScarabSwarm.ogg"}},augments:[{name:"Desiccation's Curse",description:"Desiccation cria sombras aliadas ao matar inimigos.",ability:1},{name:"Elemental Sandstorm",description:"Sandstorm aplica dano elemental baseado na arma.",ability:3},{name:"Negation Swarm",description:"Scarab Swarm remove status ao custo de armadura.",ability:4}]},

{name:"Ivara Prime",image:"https://static.wikia.nocookie.net/warframe/images/7/7c/IvaraPrime.png",abilities:{1:{name:"Quiver",sound:"https://static.wikia.nocookie.net/warframe/images/3/3e/Quiver.ogg"},2:{name:"Navigator",sound:"https://static.wikia.nocookie.net/warframe/images/9/9d/Navigator.ogg"},3:{name:"Prowl",sound:"https://static.wikia.nocookie.net/warframe/images/4/4f/Prowl.ogg"},4:{name:"Artemis Bow",sound:"https://static.wikia.nocookie.net/warframe/images/8/8e/ArtemisBow.ogg"}},augments:[{name:"Empowered Quiver",description:"Quiver concede bônus defensivos e ofensivos.",ability:1},{name:"Piercing Navigator",description:"Navigator aumenta dano de projéteis.",ability:2},{name:"Infiltrate",description:"Prowl permite atravessar lasers.",ability:3}]},

{name:"Khora Prime",image:"https://static.wikia.nocookie.net/warframe/images/8/8a/KhoraPrime.png",abilities:{1:{name:"Whipclaw",sound:"https://static.wikia.nocookie.net/warframe/images/4/4a/Whipclaw.ogg"},2:{name:"Ensnare",sound:"https://static.wikia.nocookie.net/warframe/images/3/3e/Ensnare.ogg"},3:{name:"Venari",sound:"https://static.wikia.nocookie.net/warframe/images/1/1f/Venari.ogg"},4:{name:"Strangledome",sound:"https://static.wikia.nocookie.net/warframe/images/7/7d/Strangledome.ogg"}},augments:[{name:"Pilfering Strangledome",description:"Strangledome aumenta chance de loot.",ability:4}]},

{name:"Limbo Prime",image:"https://static.wikia.nocookie.net/warframe/images/4/4f/LimboPrime.png",abilities:{1:{name:"Banish",sound:"https://static.wikia.nocookie.net/warframe/images/3/3e/Banish.ogg"},2:{name:"Stasis",sound:"https://static.wikia.nocookie.net/warframe/images/4/4f/Stasis.ogg"},3:{name:"Rift Surge",sound:"https://static.wikia.nocookie.net/warframe/images/8/8e/RiftSurge.ogg"},4:{name:"Cataclysm",sound:"https://static.wikia.nocookie.net/warframe/images/9/9d/Cataclysm.ogg"}},augments:[{name:"Rift Haven",description:"Banish cura aliados.",ability:1},{name:"Rift Torrent",description:"Rift Surge aumenta dano baseado em inimigos afetados.",ability:3}]},

{name:"Loki Prime",image:"https://static.wikia.nocookie.net/warframe/images/7/7f/LokiPrime.png",abilities:{1:{name:"Decoy",sound:"https://static.wikia.nocookie.net/warframe/images/4/4f/Decoy.ogg"},2:{name:"Invisibility",sound:"https://static.wikia.nocookie.net/warframe/images/3/3e/Invisibility.ogg"},3:{name:"Switch Teleport",sound:"https://static.wikia.nocookie.net/warframe/images/8/8d/SwitchTeleport.ogg"},4:{name:"Radial Disarm",sound:"https://static.wikia.nocookie.net/warframe/images/9/9f/RadialDisarm.ogg"}},augments:[{name:"Hushed Invisibility",description:"Invisibility silencia armas.",ability:2},{name:"Safeguard Switch",description:"Switch Teleport concede invulnerabilidade temporária.",ability:3},{name:"Irradiating Disarm",description:"Radial Disarm aplica radiação.",ability:4}]},

{name:"Mag Prime",image:"https://static.wikia.nocookie.net/warframe/images/6/6f/MagPrime.png",abilities:{1:{name:"Pull",sound:"https://static.wikia.nocookie.net/warframe/images/3/3e/Pull.ogg"},2:{name:"Magnetize",sound:"https://static.wikia.nocookie.net/warframe/images/4/4f/Magnetize.ogg"},3:{name:"Polarize",sound:"https://static.wikia.nocookie.net/warframe/images/8/8e/Polarize.ogg"},4:{name:"Crush",sound:"https://static.wikia.nocookie.net/warframe/images/9/9d/Crush.ogg"}},augments:[{name:"Greedy Pull",description:"Pull puxa loot.",ability:1},{name:"Counter Pulse",description:"Polarize desarma inimigos mecânicos.",ability:3},{name:"Fracturing Crush",description:"Crush reduz armadura.",ability:4}]},

{name:"Mesa Prime",image:"https://static.wikia.nocookie.net/warframe/images/8/8e/MesaPrime.png",abilities:{1:{name:"Ballistic Battery",sound:"https://static.wikia.nocookie.net/warframe/images/4/4f/BallisticBattery.ogg"},2:{name:"Shooting Gallery",sound:"https://static.wikia.nocookie.net/warframe/images/3/3e/ShootingGallery.ogg"},3:{name:"Shatter Shield",sound:"https://static.wikia.nocookie.net/warframe/images/8/8d/ShatterShield.ogg"},4:{name:"Peacemaker",sound:"https://static.wikia.nocookie.net/warframe/images/9/9f/Peacemaker.ogg"}},augments:[{name:"Ballistic Bullseye",description:"Ballistic Battery aumenta chance crítica.",ability:1},{name:"Muzzle Flash",description:"Shooting Gallery cega inimigos.",ability:2},{name:"Staggering Shield",description:"Shatter Shield reflete dano.",ability:3}]},

{name:"Mirage Prime",image:"https://static.wikia.nocookie.net/warframe/images/4/4f/MiragePrime.png",abilities:{1:{name:"Hall of Mirrors",sound:"https://static.wikia.nocookie.net/warframe/images/3/3e/HallOfMirrors.ogg"},2:{name:"Sleight of Hand",sound:"https://static.wikia.nocookie.net/warframe/images/4/4f/SleightOfHand.ogg"},3:{name:"Eclipse",sound:"https://static.wikia.nocookie.net/warframe/images/8/8d/Eclipse.ogg"},4:{name:"Prism",sound:"https://static.wikia.nocookie.net/warframe/images/9/9f/Prism.ogg"}},augments:[{name:"Hall of Malevolence",description:"Hall of Mirrors aumenta dano ao matar.",ability:1},{name:"Explosive Legerdemain",description:"Sleight of Hand transforma loot em bombas.",ability:2}]},

{name:"Nekros Prime",image:"https://static.wikia.nocookie.net/warframe/images/7/7f/NekrosPrime.png",abilities:{1:{name:"Soul Punch",sound:"https://static.wikia.nocookie.net/warframe/images/3/3e/SoulPunch.ogg"},2:{name:"Terrify",sound:"https://static.wikia.nocookie.net/warframe/images/4/4f/Terrify.ogg"},3:{name:"Desecrate",sound:"https://static.wikia.nocookie.net/warframe/images/8/8e/Desecrate.ogg"},4:{name:"Shadows of the Dead",sound:"https://static.wikia.nocookie.net/warframe/images/9/9d/ShadowsOfTheDead.ogg"}},augments:[{name:"Soul Survivor",description:"Soul Punch revive aliados.",ability:1},{name:"Creeping Terrify",description:"Terrify reduz velocidade.",ability:2}]},

{name:"Nezha Prime",image:"https://static.wikia.nocookie.net/warframe/images/4/4f/NezhaPrime.png",abilities:{1:{name:"Fire Walker",sound:"https://static.wikia.nocookie.net/warframe/images/3/3e/FireWalker.ogg"},2:{name:"Blazing Chakram",sound:"https://static.wikia.nocookie.net/warframe/images/4/4f/BlazingChakram.ogg"},3:{name:"Warding Halo",sound:"https://static.wikia.nocookie.net/warframe/images/8/8d/WardingHalo.ogg"},4:{name:"Divine Spears",sound:"https://static.wikia.nocookie.net/warframe/images/9/9f/DivineSpears.ogg"}},augments:[{name:"Pyroclastic Flow",description:"Fire Walker acumula dano explosivo.",ability:1},{name:"Reaping Chakram",description:"Blazing Chakram aumenta dano recebido pelos inimigos.",ability:2}]},

{name:"Nidus Prime",image:"https://static.wikia.nocookie.net/warframe/images/8/8e/NidusPrime.png",abilities:{1:{name:"Virulence",sound:"https://static.wikia.nocookie.net/warframe/images/3/3e/Virulence.ogg"},2:{name:"Larva",sound:"https://static.wikia.nocookie.net/warframe/images/4/4f/Larva.ogg"},3:{name:"Parasitic Link",sound:"https://static.wikia.nocookie.net/warframe/images/8/8d/ParasiticLink.ogg"},4:{name:"Ravenous",sound:"https://static.wikia.nocookie.net/warframe/images/9/9f/Ravenous.ogg"}},augments:[{name:"Teeming Virulence",description:"Virulence gera energia ao atingir múltiplos inimigos.",ability:1},{name:"Larva Burst",description:"Larva explode ao ser finalizada.",ability:2}]},

{name:"Nova Prime",image:"https://static.wikia.nocookie.net/warframe/images/3/3e/NovaPrime.png",abilities:{1:{name:"Null Star",sound:"https://static.wikia.nocookie.net/warframe/images/4/4f/NullStar.ogg"},2:{name:"Antimatter Drop",sound:"https://static.wikia.nocookie.net/warframe/images/7/7d/AntimatterDrop.ogg"},3:{name:"Worm Hole",sound:"https://static.wikia.nocookie.net/warframe/images/8/8e/WormHole.ogg"},4:{name:"Molecular Prime",sound:"https://static.wikia.nocookie.net/warframe/images/9/9f/MolecularPrime.ogg"}},augments:[{name:"Neutron Star",description:"Null Star pode ser recastado para explodir partículas.",ability:1},{name:"Antimatter Absorb",description:"Antimatter Drop absorve projéteis próximos.",ability:2},{name:"Escape Velocity",description:"Worm Hole concede bônus de velocidade.",ability:3},{name:"Molecular Fission",description:"Molecular Prime restaura Null Star ao matar inimigos.",ability:4}]},

{name:"Nyx Prime",image:"https://static.wikia.nocookie.net/warframe/images/4/4f/NyxPrime.png",abilities:{1:{name:"Mind Control",sound:"https://static.wikia.nocookie.net/warframe/images/3/3e/MindControl.ogg"},2:{name:"Psychic Bolts",sound:"https://static.wikia.nocookie.net/warframe/images/4/4f/PsychicBolts.ogg"},3:{name:"Chaos",sound:"https://static.wikia.nocookie.net/warframe/images/8/8d/Chaos.ogg"},4:{name:"Absorb",sound:"https://static.wikia.nocookie.net/warframe/images/9/9f/Absorb.ogg"}},augments:[{name:"Mind Freak",description:"Mind Control aumenta dano do alvo controlado.",ability:1},{name:"Pacifying Bolts",description:"Psychic Bolts desarma inimigos.",ability:2},{name:"Chaos Sphere",description:"Chaos cria área persistente de confusão.",ability:3},{name:"Assimilate",description:"Absorb permite movimento enquanto ativo.",ability:4}]},

{name:"Oberon Prime",image:"https://static.wikia.nocookie.net/warframe/images/7/7f/OberonPrime.png",abilities:{1:{name:"Smite",sound:"https://static.wikia.nocookie.net/warframe/images/3/3e/Smite.ogg"},2:{name:"Hallowed Ground",sound:"https://static.wikia.nocookie.net/warframe/images/4/4f/HallowedGround.ogg"},3:{name:"Renewal",sound:"https://static.wikia.nocookie.net/warframe/images/8/8d/Renewal.ogg"},4:{name:"Reckoning",sound:"https://static.wikia.nocookie.net/warframe/images/9/9f/Reckoning.ogg"}},augments:[{name:"Smite Infusion",description:"Smite concede dano radiação a aliados.",ability:1},{name:"Hallowed Eruption",description:"Hallowed Ground explode ao ser recastado.",ability:2},{name:"Phoenix Renewal",description:"Renewal impede morte uma vez.",ability:3},{name:"Hallowed Reckoning",description:"Reckoning cria áreas de dano.",ability:4}]},

{name:"Octavia Prime",image:"https://static.wikia.nocookie.net/warframe/images/4/4f/OctaviaPrime.png",abilities:{1:{name:"Mallet",sound:"https://static.wikia.nocookie.net/warframe/images/3/3e/Mallet.ogg"},2:{name:"Resonator",sound:"https://static.wikia.nocookie.net/warframe/images/4/4f/Resonator.ogg"},3:{name:"Metronome",sound:"https://static.wikia.nocookie.net/warframe/images/8/8d/Metronome.ogg"},4:{name:"Amp",sound:"https://static.wikia.nocookie.net/warframe/images/9/9f/Amp.ogg"}},augments:[{name:"Partitioned Mallet",description:"Mallet cria duas instâncias simultâneas.",ability:1}]},

{name:"Protea Prime",image:"https://static.wikia.nocookie.net/warframe/images/3/3e/ProteaPrime.png",abilities:{1:{name:"Grenade Fan",sound:"https://static.wikia.nocookie.net/warframe/images/4/4f/GrenadeFan.ogg"},2:{name:"Blaze Artillery",sound:"https://static.wikia.nocookie.net/warframe/images/7/7d/BlazeArtillery.ogg"},3:{name:"Dispensary",sound:"https://static.wikia.nocookie.net/warframe/images/8/8e/Dispensary.ogg"},4:{name:"Temporal Anchor",sound:"https://static.wikia.nocookie.net/warframe/images/9/9f/TemporalAnchor.ogg"}},augments:[{name:"Temporal Artillery",description:"Blaze Artillery ganha dano baseado em Temporal Anchor.",ability:2}]},

{name:"Revenant Prime",image:"https://static.wikia.nocookie.net/warframe/images/7/7f/RevenantPrime.png",abilities:{1:{name:"Enthrall",sound:"https://static.wikia.nocookie.net/warframe/images/3/3e/Enthrall.ogg"},2:{name:"Mesmer Skin",sound:"https://static.wikia.nocookie.net/warframe/images/4/4f/MesmerSkin.ogg"},3:{name:"Reave",sound:"https://static.wikia.nocookie.net/warframe/images/8/8d/Reave.ogg"},4:{name:"Danse Macabre",sound:"https://static.wikia.nocookie.net/warframe/images/9/9f/DanseMacabre.ogg"}},augments:[{name:"Blinding Reave",description:"Reave cega inimigos atingidos.",ability:3}]},
{name:"Rhino Prime",image:"https://static.wikia.nocookie.net/warframe/images/7/7f/RhinoPrime.png",abilities:{1:{name:"Rhino Charge",sound:"https://static.wikia.nocookie.net/warframe/images/3/3e/RhinoCharge.ogg"},2:{name:"Iron Skin",sound:"https://static.wikia.nocookie.net/warframe/images/4/4f/IronSkin.ogg"},3:{name:"Roar",sound:"https://static.wikia.nocookie.net/warframe/images/8/8d/Roar.ogg"},4:{name:"Rhino Stomp",sound:"https://static.wikia.nocookie.net/warframe/images/9/9f/RhinoStomp.ogg"}},augments:[{name:"Ironclad Charge",description:"Rhino Charge aumenta armadura por inimigo atingido.",ability:1},{name:"Iron Shrapnel",description:"Iron Skin pode ser detonada.",ability:2},{name:"Piercing Roar",description:"Roar aplica status puncture.",ability:3},{name:"Reinforcing Stomp",description:"Rhino Stomp restaura Iron Skin.",ability:4}]},

{name:"Saryn Prime",image:"https://static.wikia.nocookie.net/warframe/images/4/4f/SarynPrime.png",abilities:{1:{name:"Spores",sound:"https://static.wikia.nocookie.net/warframe/images/3/3e/Spores.ogg"},2:{name:"Molt",sound:"https://static.wikia.nocookie.net/warframe/images/4/4f/Molt.ogg"},3:{name:"Toxic Lash",sound:"https://static.wikia.nocookie.net/warframe/images/8/8d/ToxicLash.ogg"},4:{name:"Miasma",sound:"https://static.wikia.nocookie.net/warframe/images/9/9f/Miasma.ogg"}},augments:[{name:"Venom Dose",description:"Spores concede dano tóxico a aliados.",ability:1},{name:"Regenerative Molt",description:"Molt cura Saryn.",ability:2},{name:"Contagion Cloud",description:"Toxic Lash cria nuvens tóxicas.",ability:3}]},

{name:"Sevagoth",image:"https://static.wikia.nocookie.net/warframe/images/7/7f/Sevagoth.png",abilities:{1:{name:"Reap",sound:"https://static.wikia.nocookie.net/warframe/images/3/3e/Reap.ogg"},2:{name:"Sow",sound:"https://static.wikia.nocookie.net/warframe/images/4/4f/Sow.ogg"},3:{name:"Gloom",sound:"https://static.wikia.nocookie.net/warframe/images/8/8d/Gloom.ogg"},4:{name:"Exalted Shadow",sound:"https://static.wikia.nocookie.net/warframe/images/9/9f/ExaltedShadow.ogg"}},augments:[]},

{name:"Styanax",image:"https://static.wikia.nocookie.net/warframe/images/4/4f/Styanax.png",abilities:{1:{name:"Axios Javelin",sound:"https://static.wikia.nocookie.net/warframe/images/3/3e/AxiosJavelin.ogg"},2:{name:"Tharros Strike",sound:"https://static.wikia.nocookie.net/warframe/images/4/4f/TharrosStrike.ogg"},3:{name:"Rally Point",sound:"https://static.wikia.nocookie.net/warframe/images/8/8d/RallyPoint.ogg"},4:{name:"Final Stand",sound:"https://static.wikia.nocookie.net/warframe/images/9/9f/FinalStand.ogg"}},augments:[]},

{name:"Titania Prime",image:"https://static.wikia.nocookie.net/warframe/images/7/7f/TitaniaPrime.png",abilities:{1:{name:"Spellbind",sound:"https://static.wikia.nocookie.net/warframe/images/3/3e/Spellbind.ogg"},2:{name:"Tribute",sound:"https://static.wikia.nocookie.net/warframe/images/4/4f/Tribute.ogg"},3:{name:"Lantern",sound:"https://static.wikia.nocookie.net/warframe/images/8/8d/Lantern.ogg"},4:{name:"Razorwing",sound:"https://static.wikia.nocookie.net/warframe/images/9/9f/Razorwing.ogg"}},augments:[{name:"Beguiling Lantern",description:"Lantern aumenta dano melee.",ability:3}]},

{name:"Trinity Prime",image:"https://static.wikia.nocookie.net/warframe/images/4/4f/TrinityPrime.png",abilities:{1:{name:"Well of Life",sound:"https://static.wikia.nocookie.net/warframe/images/3/3e/WellOfLife.ogg"},2:{name:"Energy Vampire",sound:"https://static.wikia.nocookie.net/warframe/images/4/4f/EnergyVampire.ogg"},3:{name:"Link",sound:"https://static.wikia.nocookie.net/warframe/images/8/8d/Link.ogg"},4:{name:"Blessing",sound:"https://static.wikia.nocookie.net/warframe/images/9/9f/Blessing.ogg"}},augments:[{name:"Pool of Life",description:"Well of Life faz inimigos derrubarem orbes.",ability:1},{name:"Vampire Leech",description:"Energy Vampire concede escudos.",ability:2}]},

{name:"Valkyr Prime",image:"https://static.wikia.nocookie.net/warframe/images/7/7f/ValkyrPrime.png",abilities:{1:{name:"Rip Line",sound:"https://static.wikia.nocookie.net/warframe/images/3/3e/RipLine.ogg"},2:{name:"Warcry",sound:"https://static.wikia.nocookie.net/warframe/images/4/4f/Warcry.ogg"},3:{name:"Paralysis",sound:"https://static.wikia.nocookie.net/warframe/images/8/8d/Paralysis.ogg"},4:{name:"Hysteria",sound:"https://static.wikia.nocookie.net/warframe/images/9/9f/Hysteria.ogg"}},augments:[{name:"Eternal War",description:"Warcry dura mais ao matar inimigos.",ability:2},{name:"Prolonged Paralysis",description:"Paralysis aumenta alcance e duração.",ability:3}]},

{name:"Vauban Prime",image:"https://static.wikia.nocookie.net/warframe/images/4/4f/VaubanPrime.png",abilities:{1:{name:"Tesla Nervos",sound:"https://static.wikia.nocookie.net/warframe/images/3/3e/TeslaNervos.ogg"},2:{name:"Minelayer",sound:"https://static.wikia.nocookie.net/warframe/images/4/4f/Minelayer.ogg"},3:{name:"Photon Strike",sound:"https://static.wikia.nocookie.net/warframe/images/8/8d/PhotonStrike.ogg"},4:{name:"Bastille",sound:"https://static.wikia.nocookie.net/warframe/images/9/9f/Bastille.ogg"}},augments:[{name:"Repelling Bastille",description:"Bastille repele inimigos.",ability:4}]},

{name:"Volt Prime",image:"https://static.wikia.nocookie.net/warframe/images/7/7f/VoltPrime.png",abilities:{1:{name:"Shock",sound:"https://static.wikia.nocookie.net/warframe/images/3/3e/Shock.ogg"},2:{name:"Speed",sound:"https://static.wikia.nocookie.net/warframe/images/4/4f/Speed.ogg"},3:{name:"Electric Shield",sound:"https://static.wikia.nocookie.net/warframe/images/8/8d/ElectricShield.ogg"},4:{name:"Discharge",sound:"https://static.wikia.nocookie.net/warframe/images/9/9f/Discharge.ogg"}},augments:[{name:"Shock Trooper",description:"Shock concede dano elétrico a aliados.",ability:1},{name:"Shocking Speed",description:"Speed aplica dano elétrico.",ability:2},{name:"Capacitance",description:"Discharge concede escudos.",ability:4}]},

{name:"Voruna",image:"https://static.wikia.nocookie.net/warframe/images/4/4f/Voruna.png",abilities:{1:{name:"Shroud of Dynar",sound:"https://static.wikia.nocookie.net/warframe/images/3/3e/ShroudOfDynar.ogg"},2:{name:"Fangs of Raksh",sound:"https://static.wikia.nocookie.net/warframe/images/4/4f/FangsOfRaksh.ogg"},3:{name:"Lycath's Hunt",sound:"https://static.wikia.nocookie.net/warframe/images/8/8d/LycathsHunt.ogg"},4:{name:"Ulfrun's Descent",sound:"https://static.wikia.nocookie.net/warframe/images/9/9f/UlfrunsDescent.ogg"}},augments:[]},

{name:"Wisp Prime",image:"https://static.wikia.nocookie.net/warframe/images/7/7f/WispPrime.png",abilities:{1:{name:"Reservoirs",sound:"https://static.wikia.nocookie.net/warframe/images/3/3e/Reservoirs.ogg"},2:{name:"Wil-O-Wisp",sound:"https://static.wikia.nocookie.net/warframe/images/4/4f/WilOWisp.ogg"},3:{name:"Breach Surge",sound:"https://static.wikia.nocookie.net/warframe/images/8/8d/BreachSurge.ogg"},4:{name:"Sol Gate",sound:"https://static.wikia.nocookie.net/warframe/images/9/9f/SolGate.ogg"}},augments:[{name:"Fused Reservoir",description:"Reservoirs combina todos os buffs em um só.",ability:1}]},

{name:"Wukong Prime",image:"https://static.wikia.nocookie.net/warframe/images/4/4f/WukongPrime.png",abilities:{1:{name:"Celestial Twin",sound:"https://static.wikia.nocookie.net/warframe/images/3/3e/CelestialTwin.ogg"},2:{name:"Cloud Walker",sound:"https://static.wikia.nocookie.net/warframe/images/4/4f/CloudWalker.ogg"},3:{name:"Defy",sound:"https://static.wikia.nocookie.net/warframe/images/8/8d/Defy.ogg"},4:{name:"Primal Fury",sound:"https://static.wikia.nocookie.net/warframe/images/9/9f/PrimalFury.ogg"}},augments:[{name:"Celestial Stomp",description:"Celestial Twin derruba inimigos.",ability:1}]},

{name:"Xaku",image:"https://static.wikia.nocookie.net/warframe/images/7/7f/Xaku.png",abilities:{1:{name:"Xata's Whisper",sound:"https://static.wikia.nocookie.net/warframe/images/3/3e/XatasWhisper.ogg"},2:{name:"Grasp of Lohk",sound:"https://static.wikia.nocookie.net/warframe/images/4/4f/GraspOfLohk.ogg"},3:{name:"The Lost",sound:"https://static.wikia.nocookie.net/warframe/images/8/8d/TheLost.ogg"},4:{name:"The Vast Untime",sound:"https://static.wikia.nocookie.net/warframe/images/9/9f/TheVastUntime.ogg"}},augments:[]},

{name:"Yareli",image:"https://static.wikia.nocookie.net/warframe/images/4/4f/Yareli.png",abilities:{1:{name:"Sea Snares",sound:"https://static.wikia.nocookie.net/warframe/images/3/3e/SeaSnares.ogg"},2:{name:"Merulina",sound:"https://static.wikia.nocookie.net/warframe/images/4/4f/Merulina.ogg"},3:{name:"Aquablades",sound:"https://static.wikia.nocookie.net/warframe/images/8/8d/Aquablades.ogg"},4:{name:"Riptide",sound:"https://static.wikia.nocookie.net/warframe/images/9/9f/Riptide.ogg"}},augments:[]},

{name:"Zephyr Prime",image:"https://static.wikia.nocookie.net/warframe/images/7/7f/ZephyrPrime.png",abilities:{1:{name:"Tail Wind",sound:"https://static.wikia.nocookie.net/warframe/images/3/3e/TailWind.ogg"},2:{name:"Airburst",sound:"https://static.wikia.nocookie.net/warframe/images/4/4f/Airburst.ogg"},3:{name:"Turbulence",sound:"https://static.wikia.nocookie.net/warframe/images/8/8d/Turbulence.ogg"},4:{name:"Tornado",sound:"https://static.wikia.nocookie.net/warframe/images/9/9f/Tornado.ogg"}},augments:[{name:"Target Fixation",description:"Tail Wind aumenta dano ao atingir múltiplos inimigos.",ability:1}]}
];

];
